//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caps
    {
        public int ID { get; set; }
        public int ID_Manga { get; set; }
        public string NumberCap { get; set; }
        public bool SendToKindle { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Mangas Mangas { get; set; }
    }
}
