//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Download_mangas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capitulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Capitulos()
        {
            this.Paginas = new HashSet<Paginas>();
        }
    
        public int ID { get; set; }
        public int ID_Manga { get; set; }
        public int NumberOfPages { get; set; }
        public string NameCap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paginas> Paginas { get; set; }
        public virtual Mangas Mangas { get; set; }
    }
}
