//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Download_mangas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mangas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mangas()
        {
            this.Capitulos = new HashSet<Capitulos>();
            this.RelationMangaGenero = new HashSet<RelationMangaGenero>();
        }
    
        public int ID { get; set; }
        public string NameManga { get; set; }
        public int NumberOfCaps { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capitulos> Capitulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationMangaGenero> RelationMangaGenero { get; set; }
    }
}
