//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Download_mangas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyMangasEntities : DbContext
    {
        public MyMangasEntities()
            : base("name=MyMangasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capitulos> Capitulos { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Paginas> Paginas { get; set; }
        public virtual DbSet<RelationMangaGenero> RelationMangaGenero { get; set; }
        public virtual DbSet<Mangas> Mangas { get; set; }
    }
}
