//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Download_mangas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paginas
    {
        public int ID { get; set; }
        public int ID_Cap { get; set; }
        public string NumberPage { get; set; }
        public byte[] BinaryImage { get; set; }
    
        public virtual Capitulos Capitulos { get; set; }
    }
}
