//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Download_mangas
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationMangaGenero
    {
        public int ID { get; set; }
        public int ID_Manga { get; set; }
        public int ID_Genero { get; set; }
    
        public virtual Generos Generos { get; set; }
        public virtual Mangas Mangas { get; set; }
    }
}
